name: Reusable workflow

on: 
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron : '15 6 * * 0'
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        default: 'World'
        required: true
        type: string
      outputs:
        current-time: $(date)
          
jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello name to STDOUT
        run: echo Hello ${{ inputs.who-to-greet }}

      - name: Get date
        run: 
